apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-container
          image: azizche/productivity-app:client-latest
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: REACT_APP_BACKEND_URL
              value: "${REACT_APP_BACKEND_URL}"
